name: jewelry_nafisa
description: "Wearable art that captures your unique story and shines as brightly as you do"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  image: ^4.1.3
  excel: ^2.1.0
  path_provider: ^2.1.3
  flutter_svg: ^2.0.9
  firebase_core: ^3.2.0
  firebase_analytics: ^11.1.0

  # Core & State Management
  go_router: ^14.2.1
  supabase_flutter: ^2.5.0
  flutter_hooks: ^0.18.5
  hooks_riverpod: ^2.3.6
  flutter_riverpod: ^2.5.1
  provider: ^6.1.5+1
  universal_html: ^2.2.4
  http: ^1.5.0
  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  flutter_staggered_animations: ^1.1.1
  material_design_icons_flutter: ^7.0.7296
  font_awesome_flutter: ^10.7.0
  flutter_staggered_grid_view: ^0.7.0


  # Charts & Calendar
  syncfusion_flutter_charts: ^26.1.35
  syncfusion_flutter_datepicker: ^26.1.35
  table_calendar: ^3.1.2
  fl_chart: ^0.68.0
  

  # Utilities
  shared_preferences: ^2.2.3
  share_plus: ^12.0.1  
  google_sign_in: ^6.3.0
  intl_phone_field: ^3.2.0
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.2.5
  url_strategy: ^0.2.0 
  file_picker: ^8.3.3
  csv: ^6.0.0
  mime: ^1.0.4
  country_code_picker: ^3.4.1
  postcode_checker: ^1.0.2
  cached_network_image: ^3.4.1
  # REMOVED: url_launcher_web, _ios, _android (not needed)
  # REMOVED: web, universal_html (not needed by most apps)

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0 
  mockito: ^5.4.4
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/         
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  web: true
  image_path: "assets/icons/dagina2.png"